# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform NetBox installation tasks
  tags:
    - setup-all
    - setup-netbox
    - install-all
    - install-netbox
  block:
    - name: Validate NetBox configuration
      when: netbox_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install NetBox
      when: netbox_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform NetBox uninstallation tasks
  tags:
    - setup-all
    - setup-netbox
  block:
    - name: Uninstall NetBox
      when: not netbox_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
